contact:
    pattern:    /
    defaults:   { _controller: "CoyoteFrontBundle:Contact:putContact" }
    methods:    GET

fos_user_change_password:
    pattern:    /change-password
    defaults:   { _controller: "CoyoteFrontBundle:ChangePasswordFOSUser1:changePassword" }
    methods:    [GET, POST]

sonata_user_change_password:
    pattern:    /change-password
    methods:    [GET, POST]
    defaults:   { _controller: "CoyoteFrontBundle:ChangePasswordFOSUser1:changePassword" }