accueil:
    path:     /
    defaults: { _controller: CoyoteSiteBundle:Main:index }
    
CoyoteSiteBundle_coyote_main:
    resource: "@CoyoteSiteBundle/Resources/config/routing/main.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en

CoyoteSiteBundle_coyote_time:
    resource: "@CoyoteSiteBundle/Resources/config/routing/time.yml"
    prefix:   /{_locale}/time
    requirements:
        _locale: fr|en

CoyoteSiteBundle_expense:
    resource: "@CoyoteSiteBundle/Resources/config/routing/expense.yml"
    prefix:   /{_locale}/expense
    requirements:
        _locale: fr|en

CoyoteSiteBundle_admin:
    resource: "@CoyoteSiteBundle/Resources/config/routing/admin.yml"
    prefix:   /{_locale}/admin
    requirements:
        _locale: fr|en
        
CoyoteSiteBundle_profil:
    resource: "@CoyoteSiteBundle/Resources/config/routing/profil.yml"
    prefix:   /{_locale}/profile
    requirements:
        _locale: fr|en

CoyoteSiteBundle_configurator:
    resource: "@CoyoteSiteBundle/Resources/config/routing/configurator.yml"
    prefix:   /{_locale}/configurator
    requirements:
        _locale: fr|en

CoyoteSiteBundle_schedule:
    resource: "@CoyoteSiteBundle/Resources/config/routing/schedule.yml"
    prefix:   /schedule
        
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
CoyoteSiteBundle_formorder:
    resource: "@CoyoteSiteBundle/Resources/config/routing/formorder.yml"
    prefix:   /formorder
    
CoyoteSiteBundle_item:
        resource: "@CoyoteSiteBundle/Resources/config/routing/item.yml"
        prefix:   /item