coyote_site_directory:
    resource: "@CoyoteSiteBundle/Resources/config/routing/directory.yml"
    prefix:   /{_locale}/directory

CoyoteSiteBundle_absence:
    resource: "@CoyoteSiteBundle/Resources/config/routing/absence.yml"
    prefix:   /{_locale}/absence

CoyoteSiteBundle_register:
    resource: "@CoyoteSiteBundle/Resources/config/routing/register.yml"
    prefix:    /{_locale}/register
    requirements:
        _locale: fr|en|pl

CoyoteSiteBundle_contact:
    resource: "@CoyoteSiteBundle/Resources/config/routing/contact.yml"
    prefix:   /{_locale}/contact
    requirements:
        _locale: fr|en|pl

CoyoteSiteBundle_main:
    resource: "@CoyoteSiteBundle/Resources/config/routing/main.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: fr|en|pl

CoyoteSiteBundle_expense:
    resource: "@CoyoteSiteBundle/Resources/config/routing/expense.yml"
    prefix:   /{_locale}/expense
    requirements:
        _locale: fr|en|pl

CoyoteSiteBundle_admin:
    resource: "@CoyoteSiteBundle/Resources/config/routing/admin.yml"
    prefix:   /{_locale}/admin
    requirements:
        _locale: fr|en|pl

CoyoteSiteBundle_profil:
    resource: "@CoyoteSiteBundle/Resources/config/routing/profil.yml"
    prefix:   /{_locale}/profile
    requirements:
        _locale: fr|en|pl

CoyoteSiteBundle_resetting:
    resource: "@CoyoteSiteBundle/Resources/config/routing/resetting.yml"
    prefix:   /{_locale}/resetting
    requirements:
        _locale: fr|en|pl

CoyoteSiteBundle_schedule:
    resource: "@CoyoteSiteBundle/Resources/config/routing/schedule.yml"
    prefix:   /{_locale}/schedule
    requirements:
        _locale: fr|en|pl

CoyoteSiteBundle_accueil:
    path:     /
    defaults: { _controller: CoyoteSiteBundle:Main:redirect }