parameters:
#    coyote_site.example.class: Coyote\SiteBundle\Example

services:
#     coyote.site.admin.userinfo:
#         class: Coyote\SiteBundle\Admin\UserInfoAdmin
#         tags:
#             - { name: sonata.admin, manager_type: orm, label: UserInfo }
#         arguments: [null, Coyote\SiteBundle\Entity\UserInfo, CoyoteSiteBundle:UserInfoAdmin]
        
    
#    coyote_site.example:
#        class: %coyote_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
