CoyoteFrontBundle_register:
    resource: "@CoyoteFrontBundle/Resources/config/routing/register.yml"
    prefix:    /{_locale}/register
    requirements:
        _locale: fr|en|pl

CoyoteFrontBundle_contact:
    resource: "@CoyoteFrontBundle/Resources/config/routing/contact.yml"
    prefix:   /{_locale}/contact
    requirements:
        _locale: fr|en|pl

CoyoteFrontBundle_main:
    resource: "@CoyoteFrontBundle/Resources/config/routing/main.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: fr|en|pl

CoyoteFrontBundle_profil:
    resource: "@CoyoteFrontBundle/Resources/config/routing/profil.yml"
    prefix:   /{_locale}/profile
    requirements:
        _locale: fr|en|pl

CoyoteFrontBundle_resetting:
    resource: "@CoyoteFrontBundle/Resources/config/routing/resetting.yml"
    prefix:   /{_locale}/resetting
    requirements:
        _locale: fr|en|pl

CoyoteFrontBundle_accueil:
    path:     /
    defaults: { _controller: CoyoteFrontBundle:Main:redirect }

CoyoteFrontBundle_expense:
    resource: "@CoyoteExpenseBundle/Resources/config/routing/expense.yml"
    prefix:   /{_locale}/expense
    requirements:
        _locale: fr|en|pl

CoyoteFrontBundle_directory:
    resource: "@CoyoteDirectoryBundle/Resources/config/routing/directory.yml"
    prefix:   /{_locale}/directory
    requirements:
        _locale: fr|en|pl

CoyoteFrontBundle_changePassword:
    resource: "@CoyoteFrontBundle/Resources/config/routing/changePassword.yml"
    prefix: /{_locale}/profile
    requirements:
        _locale: fr|en|pl