<?php

namespace Coyote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    /**
     * findAllOrderByCode function.
     * function to find all entity currency order by code
     *
     * @access public
     * @param order by code ASC
     * @return array Currency
     */
    public function findAllOrderByCode()
    {
        return $this->findBy(array(), array('code' => 'ASC'));
    }
}
