<?php

namespace Coyote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DevisConfigurateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisConfigurateurRepository extends EntityRepository
{
    public function findNoDevis()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select ('dc.no_devis')
           ->from('CoyoteSiteBundle:DevisConfigurateur', 'dc');
        
        $nodevis = $qb->getQuery()
                      ->getResult();
        
        if(empty($nodevis))
            $nodevis = 1;
            
        $nb_devis = count($nodevis);
        return $nodevis[$nb_devis-1];
    }
}
