<?php

namespace Coyote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DirectoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends EntityRepository
{
    public function showDirectoryByFirstname($country)
    {
        return $this->findBy(array('country' => $country), array('firstname' => 'ASC'));
    }

    public function showDirectoryByFunctionService($country)
    {
        return $this->findBy(array('country' => $country), array('function_service' => 'ASC', 'firstname' => 'ASC'));
    }

    public function findAll()
    {
        return $this->findBy(array(), array('firstname' => 'ASC'));
    }
}
