<?php

namespace Coyote\SiteBundle\Entity;

use Coyote\SiteBundle\Entity\Timetable;
use Doctrine\ORM\EntityRepository;

/**
 * ScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends EntityRepository
{

    /**
     * computing working time.
     *
     * @access public
     * @param mixed $date
     * @param mixed $user
     * @return string total working time
     */
    public function findTimeMonth($date, $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s.working_time')
           ->from('CoyoteSiteBundle:Schedule', 's')
           ->innerJoin('CoyoteSiteBundle:Timetable', 't', 'WITH', 't.id = s.timetable')
           ->where('s.user = :user and t.date LIKE :date')
           ->setParameters(array('user' => $user, 'date' => $date));
        $workingtime_schedule =  $qb->getQuery()
                                    ->getResult();

        $timeend = "0";

        for($i = 0; $i<count($workingtime_schedule); $i++)
        {
            $timeend += $this->calculTime($workingtime_schedule[$i]['working_time']);
        }
        $time = $this->formatTime($timeend);
        return $time;
    }

    /**
     * find pay period .
     *
     * @access public
     * @param mixed $mois
     * @param mixed $annee
     * @return string period
     */
    public function findPeriod($mois, $annee)
    {
        if($mois >= "01" && $mois <= "05")
        {
            $anneebefore = $annee - 1;
            return $anneebefore."/".$annee;
        }
        if($mois >= "06" && $mois <= "12")
        {
            $anneenext = $annee + 1;
            return $annee."/".$anneenext;
        }
    }

    /**
     * find absence in pay period by user and specific absence.
     *
     * @access public
     * @param mixed $pay_period
     * @param mixed $user
     * @param mixed $absence
     * @return integer count absence
     */
    public function findAbsenceYear($period, $user, $absence)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s.absence_duration')
           ->from('CoyoteSiteBundle:Schedule', 's')
           ->innerJoin('CoyoteSiteBundle:Timetable', 't', 'WITH', 't.id = s.timetable')
           ->where('s.user = :user and t.period = :period and s.absence_name = :absence')
           ->setParameters(array('user' => $user, 'period' => $period, 'absence' => $absence));
        $data_absence_duration = $qb->getQuery()
                                    ->getResult();

        $count_absence = 0.0;

        for($i = 0; $i<count($data_absence_duration);$i++)
        {
            $count_absence += $data_absence_duration[$i]['absence_duration'];
        }

        return $count_absence;
    }

    /**
     * conversion time in minutes.
     *
     * @access public
     * @param mixed $time
     * @return integer minutes
     */
    public function calculTime($time)
    {
        if($time == "0:00")
            return 0;
        $time = explode(":", $time);
        $minute = $time[1];
        $heure = $time[0];
        $timefinal = $heure * 60 + $minute;
        return $timefinal;
    }

    /**
     * conversion time in hours.
     *
     * @access public
     * @param mixed $time
     * @return string
     */
    public function formatTime($time)
    {
        date_default_timezone_set('UTC');
        $time = $time * 60;

        $heures=intval($time / 3600);
        $minutes=intval(($time % 3600) / 60);
        if(strlen($minutes) < 2)
            $minutes = '0'.$minutes;

        return $heures.'h'.$minutes;
    }

    /**
     * find week and year.
     *
     * @access public
     * @param mixed $pay_period
     * @param mixed $user
     * @return array pay_period, user
     */
    public function findNoWeekPayPeriod($pay_period, $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('distinct(t.no_week) as no_week, t.year')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.pay_period = :pay_period and s.user = :user')
           ->orderBy('s.timetable')
           ->setParameters(array('pay_period' => $pay_period, 'user' => $user));
        $time =  $qb->getQuery()
                    ->getResult();
        return $time;
    }

    /**
     * pre save schedule for technician user.
     *
     * @access public
     * @param mixed $user
     * @param mixed $timetable_id
     * @param mixed $time_start
     * @param mixed $time_end
     * @param mixed $time_break
     * @param mixed $time_travel
     * @param mixed $time_absence
     * @param mixed $time_comment
     * @return entity Schedule
     */
    public function saveSchedule($user, $timetable_id, $time_start, $time_end, $time_break, $time_travel, $time_absence,
        $time_absenceday, $time_absencetime, $time_comment)
    {
        if(empty($time_start) && empty($time_end) && empty($time_break) && empty($time_travel) && empty($time_comment)
            && ($time_absence == "Aucune"))
            return null;
        $schedule = new Schedule();

        $schedule->setUser($user);
        $schedule->setTimetable($timetable_id);

        if(empty($time_start))
            $time_start = '0:00';
        $schedule->setStart($time_start);

        if(empty($time_end))
            $time_end = '0:00';
        $schedule->setEnd($time_end);

        if(empty($time_break))
            $time_break = '0:00';
        $schedule->setBreak($time_break);

        $timetable = new Timetable();

        $working_time_day = $timetable->working_time_day($time_start, $time_end, $time_break);

        $schedule->setWorkingTime($working_time_day);
        $working_hours_day = $timetable->working_hours_day($working_time_day);
        $schedule->setWorkingHours($working_hours_day);
        if($time_travel == "on")
            $time_travel = 1;
        else
            $time_travel = 0;
        $schedule->setTravel($time_travel);
        $schedule->setAbsenceName($time_absence);
        if($time_absenceday == "0.5" || $time_absenceday == "1")
            $schedule->setAbsenceDuration($time_absenceday);
        if($time_absenceday == "empty")
            $schedule->setAbsenceDuration($time_absencetime);
        $schedule->setComment($time_comment);
        return $schedule;
    }

    /**
     * pre update schedule for technician user.
     *
     * @access public
     * @param mixed $schedule
     * @param mixed $time_start
     * @param mixed $time_end
     * @param mixed $time_break
     * @param mixed $time_travel
     * @param mixed $time_absence
     * @param mixed $time_comment
     * @return entity Schedule
     */
    public function updateSchedule($schedule, $time_start, $time_end, $time_break, $time_travel, $time_absence,
        $time_absenceday, $time_absencetime, $time_comment)
    {
        $timetable = new timetable();
        if(empty($time_start))
            $time_start = '0:00';

        if(empty($time_end))
            $time_end = '0:00';

        if(empty($time_break))
            $time_break = '0:00';
        $schedule->setBreak($time_break);
        $schedule->setStart($time_start);
        $schedule->setEnd($time_end);
        $schedule->setBreak($time_break);
        $working_time_day = $timetable->working_time_day($time_start, $time_end, $time_break);
        $schedule->setWorkingTime($working_time_day);
        $working_hours_day = $timetable->working_hours_day($working_time_day);
        $schedule->setWorkingHours($working_hours_day);
        if($time_travel == "on")
            $time_travel = 1;
        else
            $time_travel = 0;
        $schedule->setTravel($time_travel);
        $schedule->setAbsenceName($time_absence);
        if($time_absenceday == "0.5" || $time_absenceday == "1")
            $schedule->setAbsenceDuration($time_absenceday);
        if($time_absenceday == "empty")
            $schedule->setAbsenceDuration($time_absencetime);
        $schedule->setComment($time_comment);
        return $schedule;
    }

    /**
     * pre save schedule for framework user.
     *
     * @access public
     * @param mixed $user
     * @param mixed $timetable_id
     * @param mixed $time_travel
     * @param mixed $time_absence
     * @param mixed $time_comment
     * @param mixed $day
     * @return entity Shcedule
     */
    public function saveSchedulefm($user, $timetable_id, $time_travel, $time_absence, $time_absenceday,
        $time_absencetime, $time_comment, $day)
    {
        if(empty($day) && empty($time_travel) && empty($time_comment)
            && ($time_absence == "Aucune"))
            return null;
        $schedule = new schedule();
        $schedule->setUser($user);
        $schedule->setTimetable($timetable_id);
        $schedule->setStart("0:00");
        $schedule->setEnd("0:00");
        $schedule->setBreak("0:00");
        $schedule->setWorkingTime("0:00");
        $schedule->setWorkingHours($day);
        if($time_travel == "on")
            $time_travel = 1;
        else
            $time_travel = 0;
        $schedule->setTravel($time_travel);
        $schedule->setAbsenceName($time_absence);
        if($time_absenceday == "0.5" || $time_absenceday == "1")
            $schedule->setAbsenceDuration($time_absenceday);
        if($time_absenceday == "empty")
        {
            if($time_absencetime == "undef")
                $schedule->setAbsenceDuration('');
            else
                $schedule->setAbsenceDuration($time_absencetime);
        }
        $schedule->setComment($time_comment);
        return $schedule;
    }

    /**
     * pre update schedule for framework user.
     *
     * @access public
     * @param mixed $schedule
     * @param mixed $time_travel
     * @param mixed $time_absence
     * @param mixed $time_comment
     * @param mixed $day
     * @return entity Schedule
     */
    public function updateSchedulefm($schedule, $time_travel, $time_absence, $time_absenceday, $time_absencetime,
        $time_comment, $day)
    {
        $schedule->setWorkingHours($day);
        if($time_travel == "on")
            $time_travel = 1;
        else
            $time_travel = 0;
        $schedule->setTravel($time_travel);
        $schedule->setAbsenceName($time_absence);
        if($time_absenceday == "0.5" || $time_absenceday == "1")
            $schedule->setAbsenceDuration($time_absenceday);
        if($time_absenceday == "empty")
        {
            if($time_absencetime == "undef")
                $schedule->setAbsenceDuration('');
            else
                $schedule->setAbsenceDuration($time_absencetime);
        }
        $schedule->setComment($time_comment);
        return $schedule;
    }

    /**
     * data schedule for technician user.
     *
     * @access public
     * @param mixed $user
     * @param mixed $date
     * @return array Schedule, Timetable
     */
    public function dataSchedule($user, $date)
    {
        $datestart = $date."01";
        $date = $date."%";
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t.date, s.start, s.end, s.break, s.working_time, s.working_hours, s.travel, s.absence_name,
            s.absence_duration, s.comment , t.holiday')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.date LIKE :date and s.user = :user ')
           ->orderBy('s.timetable')
           ->setParameters(array('date' => $date, 'user' => $user, ));
        $dataschedule =  $qb->getQuery()
                            ->getResult();
        return $dataschedule;
    }

    public function timeWeek($dataschedule)
    {
        if(count($dataschedule)>0)
        {
            $week = $dataschedule[0]['date']->format('W');
            $index = 0;
            $value = 0;
            $timeweek = '';
            $count_item = count($dataschedule)-1;
            for($i=0;$i<count($dataschedule);$i++)
            {
                if($week == $dataschedule[$i]['date']->format('W'))
                {
                    $value += $this->calculTime($dataschedule[$i]['working_time']);
                    $week = $dataschedule[$i]['date']->format('W');
                }
                if($count_item == $i)
                {
                    $timeweek[$index] = $this->formatTime($value);
                    $value=0;
                    $index++;
                    $value += $this->calculTime($dataschedule[$i]['working_time']);
                    $timeweek[$index] = $this->formatTime($value);
                }
                if($week != $dataschedule[$i]['date']->format('W'))
                {
                    $timeweek[$index] = $this->formatTime($value);
                    $value=0;
                    $index++;
                    $value += $this->calculTime($dataschedule[$i]['working_time']);
                    $week = $dataschedule[$i]['date']->format('W');
                }
            }
        }
        else
            $timeweek = '';
        return $timeweek;
    }

    /**
     * data schedule for framework user .
     *
     * @access public
     * @param mixed $user
     * @param mixed $date
     * @return array Schedule, Timetable
     */
    public function dataScheduleFM($user, $date)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t.date, s.working_hours, s.travel, s.absence_name, s.absence_duration, s.comment,
            t.holiday')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.date LIKE :date and s.user = :user')
           ->orderBy('s.timetable')
           ->setParameters(array('date' => $date, 'user' => $user));
        $dataschedule =  $qb->getQuery()
                            ->getResult();
        return $dataschedule;
    }

    /**
     * find count absence
     *
     * @access public
     * @param mixed $date
     * @param mixed $user
     * @param mixed $absence
     * @return float
     */
    public function absenceMonth($date, $user, $absence)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s.absence_duration')
           ->from('CoyoteSiteBundle:Schedule', 's')
           ->innerJoin('CoyoteSiteBundle:Timetable', 't', 'WITH', 't.id = s.timetable')
           ->where('s.user = :user and t.date LIKE :date and s.absence_name = :absence')
           ->setParameters(array('user' => $user, 'date' => $date, 'absence' => $absence));
        $data_absence_duration = $qb->getQuery()
                                    ->getResult();

        $count_absence = 0.0;

        for($i = 0; $i<count($data_absence_duration);$i++)
        {
            $count_absence += $data_absence_duration[$i]['absence_duration'];
        }

        return $count_absence;
    }

    /**
     * find count working day in month.
     *
     * @access public
     * @param mixed $date
     * @param mixed $user
     * @return float
     */
    public function findDayMonth($date, $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s.working_hours')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.date LIKE :date and s.user = :user')
           ->setParameters(array('date' => $date, 'user' => $user));
        $data_working_hours = $qb->getQuery()
                                 ->getResult();
        $working_day = 0.0;
        foreach($data_working_hours as $value)
        {
            $working_day = $working_day + $value['working_hours'];
        }
        return $working_day;
    }

    /**
     * find count working day in year
     *
     * @access public
     * @param mixed $period
     * @param mixed $user
     * @return float
     */
    public function findDayYear($period, $user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s.working_hours')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.period = :period and s.user = :user')
           ->setParameters(array('period' => $period, 'user' => $user));
        $data_working_hours = $qb->getQuery()
                                 ->getResult();
        $working_day = 0.0;
        foreach($data_working_hours as $value)
        {
            $working_day = $working_day + $value['working_hours'];
        }
        return $working_day;
    }


    /**
     * dataScheduleYear function.
     * data schedule technician user
     *
     * @access public
     * @param mixed $user
     * @param mixed $period
     * @return array Schedule, Timetable
     */
    public function dataScheduleYear($user, $period)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t.date, s.start, s.end, s.break, s.working_time, s.working_hours, s.travel, s.absence_name,
            s.absence_duration, s.comment , t.holiday')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.period = :period and s.user = :user')
           ->orderBy('s.timetable')
           ->setParameters(array('period' => $period, 'user' => $user));
        $dataschedule =  $qb->getQuery()
                            ->getResult();
        return $dataschedule;
    }


    /**
     * dataScheduleFMYear function.
     * data schedule framework user
     *
     * @access public
     * @param mixed $user
     * @param mixed $period
     * @return array Schedule, Timetable
     */
    public function dataScheduleFMYear($user, $period)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t.date, s.working_hours, s.travel, s.absence_name, s.absence_duration, s.comment ,
            t.holiday')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.period = :period and s.user = :user')
           ->orderBy('s.timetable')
           ->setParameters(array('period' => $period, 'user' => $user));
        $dataschedule =  $qb->getQuery()
                            ->getResult();
        return $dataschedule;
    }

    /**
     * find week with date and user.
     *
     * @access private
     * @param mixed $date
     * @param mixed $user
     * @return array Timetable no_week
     */
    private function findNoWeek($date)
    {
        $query = $this->getEntityManager()
                      ->createQuery("
                        select distinct(t.no_week) from CoyoteSiteBundle:Timetable t
                        where t.date_name like :date ");
        $query->setParameters(array('date' => $date));

        $timetable_noweek = $query->getResult();

        return $timetable_noweek;
    }


    /**
     * calculOvertime function.
     *
     * @access public
     * @param mixed $count_time
     * @param mixed $working_time_month
     * @param mixed $count_absence
     * @return string
     */
    public function calculOvertime($count_time, $working_time_month, $count_absence)
    {
        $value_month = array(1 => 8, 2=> 9, 3 => 10, 4=> 11, 5 => 12, 6=> 1, 7 => 2, 8=> 3, 9 => 4, 10=> 5, 11 => 6,
            12=> 7);
        $month = date("n");
        if($month == 1)
            $month = 12;
        else
            $month--;

        $count_time = $count_time - $count_absence - (5*$value_month[$month]);
        $count_time = $count_time * 7;
        $time_month = $count_time * 60;
        $time_work = $this->calculTime($working_time_month);
        $difference = $time_work - $time_month;
        return $this->formatTime($difference);
    }


    /**
     * sumWorkingTimeMonth function.
     * function to calculate working time by month
     *
     * @access public
     * @param mixed $date
     * @param mixed $user
     * @return string
     */
    public function sumWorkingTimeMonth($date, $user)
    {
        $datefin = date("Y-m-d H:i:s", mktime(23,59,59,date("m"),0,date("Y")));
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s.working_time')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.date > :date and t.date < :datefin and s.user = :user')
           ->setParameters(array('date' => $date, 'user' => $user, 'datefin' => $datefin));
        $working_time_month =  $qb->getQuery()
                                  ->getResult();
        $timetotal = "";
        for($i=0;$i<count($working_time_month);$i++)
        {
            $timetotal += $this->calculTime($working_time_month[$i]['working_time']);
        }
        return $this->formatTimeDB($timetotal);
    }


    /**
     * formatTimeDB function.
     * convert string in datetime
     *
     * @access public
     * @param mixed $time
     * @return void
     */
    public function formatTimeDB($time)
    {
        date_default_timezone_set('UTC');
        $time = $time * 60;

        $heures=intval($time / 3600);
        $minutes=intval(($time % 3600) / 60);
        if(strlen($minutes) < 2)
            $minutes = '0'.$minutes;

        return $heures.':'.$minutes;
    }


    /**
     * countAbsence function.
     * function to calculate working day
     *
     * @access public
     * @param mixed $date
     * @param mixed $user
     * @return integer
     */
    public function countAbsence($date, $user)
    {
        $datefin = date("Y-m-d H:i:s", mktime(23,59,59,date("m"),0,date("Y")));
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t')
           ->from('CoyoteSiteBundle:Timetable', 't')
           ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
           ->where('t.holiday = :holiday and s.user = :user and
                s.absence_name != :absence1 and s.absence_name != :absence2 and t.date BETWEEN :date and :datefin')
           ->setParameters(array('date' => $date, 'datefin' => $datefin, 'holiday' => '0','user' => $user,
                'absence1' => 'Aucune', 'absence2' => 'Recup'));
        $timetable =  $qb->getQuery()
                         ->getResult();
        return count($timetable);
    }


    /**
     * dataFileBE function.
     * function to retrieve data about user be
     *
     * @access public
     * @param mixed $user
     * @param mixed $date
     * @return array Timetable, Schedule
     */
    public function dataFileBE($user, $date)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('t.no_week, t.date, s.start, s.end, s.break, s.working_time, s.working_hours, s.comment,
            s.travel, s.absence_name')
               ->from('CoyoteSiteBundle:Timetable', 't')
               ->innerJoin('CoyoteSiteBundle:Schedule', 's', 'WITH', 't.id = s.timetable')
               ->where('t.date LIKE :date and s.user = :user')
               ->setParameters(array('date' => $date, 'user' => $user));
            $timetableschedule = $qb->getQuery()->getResult();
            return $timetableschedule;
    }


    /**
     * nameUser function.
     *
     * @access public
     * @param mixed $user
     * @return string
     */
    public function nameUser($user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u.name')
               ->from('CoyoteSiteBundle:User', 'u')
               ->where('u.id = :user')
               ->setParameters(array('user' => $user));
        $user_name = $qb->getQuery()->getResult();
        return $user_name;
    }


    /**
     * fileDataUserBE function.
     * function to generate string with data user BE
     *
     * @access public
     * @param mixed $tab_user_id
     * @param mixed $month
     * @param mixed $year
     * @return string
     */
    public function fileDataUserBE($tab_user_id, $month, $year)
    {
        $qb = $this->_em->createQueryBuilder();
        $result = "";
        $no_week = 0;

        foreach($tab_user_id as $user_id)
        {
            $timetableschedule = $this->dataFileBE($user_id, $year.'-'.$month.'-%');

            $timeres = 0;
            $index = 0;

            $user_name = $this->nameUser($user_id);

            $result .= $user_name[0]['name'].";\r\n\r\n";

            foreach($timetableschedule as $data)
            {
                if($no_week != 0 && $data['no_week'] != $no_week)
                {
                    $result .= "Temps de travail de la semaine : ".$this->formatTime($timeres).";\r\n\r\n";
                    $timeres = 0;
                }
                $no_week = $data['no_week'];
                $result .= $data['day'].';'.$data['date']->format('Y-m-d').';';
                $result .= $data['start'].";".$data['end'].";".$data['break'].";".$data['working_time'].";";
                $result .= $data['working_hours'].";";
                $result .= $data['travel'].";".$data['absence_name'].";".$data['comment'].";\r\n";
                $timeres += $this->calculTime($data['working_time']).";\r\n";
                if ($data === end($timetableschedule))
                {
                    $result .= "Temps de travail de la semaine : ".$this->formatTime($timeres).";\r\n\r\n";
                    $timeres = 0;
                }
            }
        }
        return $result;
    }

    public function timeData($timetable, $user )
    {
        $index = 0;
        foreach($timetable as $data)
        {
            $qb = $this->_em->createQueryBuilder();
            $qb->select('s')
                   ->from('CoyoteSiteBundle:Schedule', 's')
                   ->where('s.user = :user and s.timetable = :timetable')
                   ->setParameters(array('user' => $user, 'timetable' => $data));
            $result = $qb->getQuery()->getOneOrNullResult();//$qb->getQuery()->getResult();
            if($result == null)
                $time[$index] = array();
            else
                $time[$index] = $result;
            $index++;
        }
        return $time;
    }

    public function absenceByUser($user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
               ->from('CoyoteSiteBundle:Schedule', 's')
               ->where('s.user = :user and not s.absence_name = :absence')
               ->setParameters(array(
               'user' => $user,
               'absence'  => 'Aucune',
               ));
        $entities = $qb->getQuery()->getResult();
        return $entities;
    }
}