<?php

namespace Coyote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
     * updateRole function.
     * function to add or remove roles
     *
     * @access public
     * @param mixed $user
     * @param mixed $roles
     * @param mixed $option
     * @return void
     */
    public function updateRole($user, $roles, $option)
    {
        if($option == "add")
        {
            foreach ($roles as $value){
                switch ($value) {
                    case 'Tech':
                        $user->addRole('ROLE_TECH');
                        break;
                    case 'Cadre':
                        $user->addRole('ROLE_CADRE');
                        break;
                    case 'Trade':
                        $user->addRole('ROLE_TRADE');
                        break;
                    case 'BE':
                        $user->addRole('ROLE_CHEF_BE');
                        break;
                    case 'Compta':
                        $user->addRole('ROLE_COMPTA');
                        break;
                }
            }
        }
        if($option == "remove")
        {
            foreach ($roles as $value){
                switch ($value) {
                    case 'Tech':
                        $user->removeRole('ROLE_TECH');
                        break;
                    case 'Cadre':
                        $user->removeRole('ROLE_CADRE');
                        break;
                    case 'Trade':
                        $user->removeRole('ROLE_TRADE');
                        break;
                    case 'BE':
                        $user->removeRole('ROLE_CHEF_BE');
                        break;
                    case 'Compta':
                        $user->removeRole('ROLE_COMPTA');
                        break;
                }
            }
        }
        $this->_em->persist($user);
        $this->_em->flush();
        return "OK";
    }

    /**
     * findAllOrderByName function.
     * function to find all entity business order by name
     *
     * @access public
     * @param order by name ASC
     * @return array Business
     */
    public function findAllOrderById()
    {
        return $this->findBy(array('enabled' => 1), array('id' => 'ASC'));
    }
}
