# FOSUserBundle Configuration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    Coyote\SiteBundle\Entity\User # La classe de l'entité User que nous utilisons
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: Coyote\SiteBundle\Form\RegistrationType
            # if you are using Symfony < 2.8 you should use the type name instead
            # type: app_user_registration