coyote_site:
    resource: "@CoyoteSiteBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin