admin_exportexpense:
    pattern:    /exportexpense
    defaults:   { _controller: "CoyoteSiteBundle:Admin:getexportExpense" }

admin_exportdatauser:
    pattern:    /exportdatauser
    defaults:   { _controller: "CoyoteSiteBundle:Admin:getexportDataUser" }

admin_updateroles:
    pattern:    /updateroles
    defaults:   { _controller: "CoyoteSiteBundle:Admin:postrolesUser" }

admin_indexchoicesuser:
    pattern:    /indexchoicesuser
    defaults:   { _controller: "CoyoteSiteBundle:Admin:getchoicesUser" }

admin_choicesroles:
    pattern:    /choicesroles
    defaults:   { _controller: "CoyoteSiteBundle:Admin:postchoicesrolesUser" }

admin_showadmin:
    pattern:    /showadmin/{page}
    defaults:   { _controller: "CoyoteSiteBundle:Admin:getExpenses", page: 1 }
    requirements:
        page:  \d+

admin_getscheduleuser:
    pattern:    /getscheduleuser
    defaults:   { _controller: "CoyoteSiteBundle:Admin:getScheduleUser" }