registration_register:
    pattern:  /
    defaults: { _controller: "CoyoteSiteBundle:Registration:register" }

registration_check_email:
    pattern: /check-email
    defaults: { _controller: "CoyoteSiteBundle:Registration:check_email" }
    requirements: { _method: get }

registration_confirm:
    pattern:    /confirm/{token}
    defaults: { _controller: "CoyoteSiteBundle:Registration:confirm" }
    requirements: { _method: get }

registration_confirmed:
    pattern: /confirmed
    defaults: { _controller: "CoyoteSiteBundle:Registration:confirmed" }
    requirements: { _method: get }