Coyote\SiteBundle\Entity\Business:
    type: entity
    table: business
    repositoryClass: Coyote\SiteBundle\Entity\BusinessRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        code:
            type: string
            lenght: 10
            unique: true
            notnull: true
        name:
            type: string
            lenght: 45
            notnull: true
    oneToMany:
        expenses:
            targetEntity: Expense
            mappedBy: business
            cascade: ["persist", "merge"]