Coyote\SiteBundle\Entity\CommentsSale:
    type: entity
    table: comments_sale
    repositoryClass: Coyote\SiteBundle\Entity\CommentSaleRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        comment:
            type: string
            lenght: 1000
    manyToOne:
        languages:
            targetEntity: Languages
            inversedBy: comments_sales
            joinColumn:
                name: languages_id
                referencedColumnName: id
    oneToMany:
        offer_contents:
            targetEntity: OfferContent
            mappedBy: comments_sale
            cascade: ["persist", "merge"]