Coyote\SiteBundle\Entity\DeliveryAddress:
    type: entity
    table: deliveryaddress
    repositoryClass: Coyote\SiteBundle\Entity\DeliveryAddressRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        corporate_name:
            type: string
            lenght: 80
        name:
            type: string
            lenght: 80
        adress1:
            type: string
            lenght: 45
        adress2:
            type: string
            lenght: 45
        zip_code:
            type: string
            lenght: 10
        postal_box:
            type: string
            lenght: 10
        city:
            type: string
            lenght: 80
        country:
            type: string
            lenght: 45
        phone:
            type: string
            lenght: 20
        cell:
            type: string
            lenght: 20
        fax:
            type: string
            length: 20
        email:
            type: string
            lenght: 100
    oneToMany:
        formorders:
            targetEntity: FormOrder
            mappedBy: deliveryaddress
            cascade: ["persist", "merge"]