Coyote\SiteBundle\Entity\Fee:
    type: entity
    table: fee
    repositoryClass: Coyote\SiteBundle\Entity\FeeRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        code:
            type: string
            lenght: 6
            unique: true
            notnull: true
        name:
            type: string
            lenght: 45
            notnull: true
        rate:
            type: float
            notnull: true
        code_rate:
            type: string
            lenght: 4
            notnull: true
    oneToMany:
        expenses:
            targetEntity: Expense
            mappedBy: fee
            cascade: ["persist", "merge"]