Coyote\SiteBundle\Entity\FormOrder:
    type: entity
    table: formorder
    repositoryClass: Coyote\SiteBundle\Entity\FormOrderRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        ordernumber:
            type: integer
            notnull: true
        created_at:
            type: datetime
            notnull: true
        amount:
            type: integer
            lenght: 10
            notnull: true
    manyToOne:
        item:
            targetEntity: Item
            inversedBy: formorders
            joinColumn:
                name: item_id
                referencedColumnName: id
        transport:
            targetEntity: Transport
            inversedBy: formorders
            joinColumn:
                name: transport_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: formorders
            joinColumn:
                name: user_id
                referencedColumnName: id
        deliveryaddress:
            targetEntity: DeliveryAddress
            inversedBy: formorders
            joinColumn:
                name: deliveryaddress_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]