Coyote\SiteBundle\Entity\IndiceVitesse:
    type: entity
    table: indice_vitesse
    repositoryClass: Coyote\SiteBundle\Entity\IndiceVitesseRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        symobole_vitesse:
            type: string
            lenght: 255
        vitesse:
            type: integer
            lenght: 11
        type:
            type: string
            lenght: 255
        categorie:
            type: string
            lenght: 255