Coyote\SiteBundle\Entity\IndiceCharge:
    type: entity
    table: indice_charge
    repositoryClass: Coyote\SiteBundle\Entity\IndiceChargeRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        indice_charge:
            type: integer
            lenght: 11
        charge:
            type: integer
            lenght: 11
        type:
            type: string
            lenght: 255
        categorie:
            type: string
            lenght: 255