Coyote\SiteBundle\Entity\OfferHeader:
    type: entity
    table: offer_header
    repositoryClass: Coyote\SiteBundle\Entity\OfferHeaderRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        created_at:
            type: string
            lenght: 10
        updated_at:
            type: string
            lenght: 10
        expires_at:
            type: string
            lenght: 10
        customer_number:
            type: string
            lenght: 3
        customer_information:
            type: string
            lenght: 80
        discount:
            type: float
        prices_reach:
            type: float
        total_price:
            type: float
        total_price_currency:
            type: float
        exchange_rate:
            type: float
        delivery_date:
            type: string
            lenght: 10
        TVA_rate:
            type: float
    manyToOne:
        user:
            targetEntity: User
            inversedBy: offer_headers
            joinColumn:
                name: user_id
                referencedColumnName: id
        languages:
            targetEntity: Languages
            inversedBy: offer_headers
            joinColumn:
                name: language_id
                referencedColumnName: id
        currency:
            targetEntity: Currency
            inversedBy: offer_headers
            joinColumn:
                name: currency_id
                referencedColumnName: id
    oneToMany:
        offer_contents:
            targetEntity: OfferContent
            mappedBy: offer_header
            cascade: ["persist", "merge"]