Coyote\SiteBundle\Entity\Schedule:
    type: entity
    table: schedule
    repositoryClass: Coyote\SiteBundle\Entity\ScheduleRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        start:
            type: string
            lenght: 8
            notnull: true
        end:
            type: string
            lenght: 8
            notnull: true
        break:
            type: string
            lenght: 8
            notnull: true
        working_time:
            type: string
            lenght: 8
            notnull: true
        working_hours:
            type: float
            notnull: true
        travel:
            type: boolean
            notnull: true
        absence_name:
            type: string
            notnull: true
            lenght: 50
        absence_duration:
            null: true
            type: string
            lenght: 10
        comment:
            type: string
            lenght: 255
    manyToOne:
        user:
            targetEntity: User
            inversedBy: schedules
            joinColumn:
                name: user_id
                referencedColumnName: id
        timetable:
            targetEntity: Timetable
            inversedBy: schedules
            joinColumn:
                name: timetable_id
                referencedColumnName: id