Coyote\SiteBundle\Entity\Site:
    type: entity
    table: site
    repositoryClass: Coyote\SiteBundle\Entity\SiteRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        code:
            type: string
            lenght: 3
            unique: true
            notnull: true
        name:
            type: string
            lenght: 45
            notnull: true
    oneToMany:
        expenses:
            targetEntity: Expense
            mappedBy: site
            cascade: ["persist", "merge"]