Coyote\SiteBundle\Entity\Transport:
    type: entity
    table: transport
    repositoryClass: Coyote\SiteBundle\Entity\TransportRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            lenght: 255
            notnull: true
    oneToMany:
        formorders:
            targetEntity: FormOrder
            mappedBy: transport
            cascade: ["persist", "merge"]