Coyote\SiteBundle\Entity\Transmission:
    type: entity
    table: transmission
    repositoryClass: Coyote\SiteBundle\Entity\TransmissionRepository
    id:
        id:
            type: integer
            unique: true
            generator: { strategy: AUTO }
    fields:
        code:
            type: integer
            lenght: 11
        designation:
            type: string
            lenght: 255
        puissance:
            type: string
            lenght: 255
        prix_ht:
            type: string(255)
        type:
            type: string(255)
        categorie:
            type: string(255)