Coyote\SiteBundle\Entity\User:
    type:   entity
    table:  user
    repositoryClass: Coyote\SiteBundle\Entity\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            lenght: 80
        adress1:
            type: string
            lenght: 45
        adress2:
            type: string
            lenght: 45
        zip_code:
            type: string
            lenght: 10
        postal_box:
            type: string
            lenght: 10
        city:
            type: string
            lenght: 80
        country:
            type: string
            lenght: 45
        phone:
            type: string
            lenght: 20
        cell:
            type: string
            lenght: 20
        fax:
            type: string
            length: 20
        website:
            type: string
            lenght: 100
    oneToMany:
        schedules:
            targetEntity: Schedule
            mappedBy: user
            cascade: ["persist", "merge"]
        offer_headers:
            targetEntity: OfferHeader
            mappedBy: user
            cascade: ["persist", "merge"]
        userfeess:
            targetEntity: UserFees
            mappedBy: user
            cascade: ["persist", "merge"]
        formorders:
            targetEntity: FormOrder
            mappedBy: user
            cascade: ["persist", "merge"]