admin_exportexpense:
    pattern:    /exportexpense
    defaults:   { _controller: "CoyoteSiteBundle:Admin:exportExpense" }

admin_export_index:
    pattern:    /index
    defaults:   { _controller: "CoyoteSiteBundle:Admin:showexport" }

admin_exportdatauser:
    pattern:    /exportdatauser
    defaults:   { _controller: "CoyoteSiteBundle:Admin:exportDataUser" }

admin_updateroles:
    pattern:    /updateroles
    defaults:   { _controller: "CoyoteSiteBundle:Admin:updateroles" }

admin_indexchoicesuser:
    pattern:    /indexchoicesuser
    defaults:   { _controller: "CoyoteSiteBundle:Admin:indexchoicesuser" }

admin_choicesroles:
    pattern:    /choicesroles
    defaults:   { _controller: "CoyoteSiteBundle:Admin:choicesroles" }

admin_showadmin:
    pattern:    /showadmin/{page}
    defaults:   { _controller: "CoyoteSiteBundle:Expense:showadmin", page: 1 }
    requirements:
        page:  \d+