configurator:
    pattern:    /
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:index" }

configurator_pagedeux:
    pattern:    /page2
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:pagedeux"}

configurator_pagetrois:
    pattern:    /page3
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:pagetrois"}

configurator_pagequatre:
    pattern:    /page4
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:pagequatre"}

configurator_pagecinq:
    pattern:    /page5
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:pagecinq"}

configurator_pagesix:
    pattern:    /page6
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:pagesix"}

configurator_pagesept:
    pattern:    /page7
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:pagesept"}

configurator_pagehuit:
    pattern:    /page8
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:pagehuit"}

configurator_pageneuf:
    pattern:    /page9
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:pageneuf"}

configurator_next:
    pattern:    /next
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:addconfig" }

configurator_show:
    pattern:    /show
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:show" }

configurator_code:
    pattern:    /code
    defaults:   { _controller: "CoyoteSiteBundle:Configurator:code" }