expense_index:
    pattern:    /
    defaults:   { _controller: "CoyoteSiteBundle:Expense:index"}

expense_create:
    pattern:    /create
    defaults:   { _controller: "CoyoteSiteBundle:Expense:create"}

expense_save:
    pattern:    /save
    defaults:   { _controller: "CoyoteSiteBundle:Expense:save"}
    requirements:
        _method:    POST

expense_show:
    pattern:    /show
    defaults:   { _controller: "CoyoteSiteBundle:Expense:show"}
    requirements: { _method: get }

expense_showparameters:
    pattern:    /show/{year}/{month}
    defaults:   { _controller: "CoyoteSiteBundle:Expense:showparameters"}
    requirements: { _method: get }

expense_print:
    pattern:    /print
    defaults:   { _controller: "CoyoteSiteBundle:Expense:print"}

expense_indexshow:
    pattern:    /indexshow
    defaults:   { _controller: "CoyoteSiteBundle:Expense:indexshow"}

expense_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CoyoteSiteBundle:Expense:edit" }

expense_update:
    pattern:  /{id}/update
    defaults: { _controller: "CoyoteSiteBundle:Expense:update" }
    requirements: { _method: post|put }

expense_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CoyoteSiteBundle:Expense:delete" }
    requirements: { _method: post|delete }