holiday:
    path:     /
    defaults: { _controller: "CoyoteSiteBundle:Holiday:index" }

holiday_show:
    path:     /show
    defaults: { _controller: "CoyoteSiteBundle:Holiday:show" }

holiday_new:
    path:     /new
    defaults: { _controller: "CoyoteSiteBundle:Holiday:new" }

holiday_create:
    path:     /create
    defaults: { _controller: "CoyoteSiteBundle:Holiday:create" }
    requirements: { _method: post }

holiday_edit:
    path:     /edit
    defaults: { _controller: "CoyoteSiteBundle:Holiday:edit" }

holiday_update:
    path:     /update
    defaults: { _controller: "CoyoteSiteBundle:Holiday:update" }
    requirements: { _method: post|put }

#holiday_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "CoyoteSiteBundle:Holiday:delete" }
#    requirements: { _method: post|delete }
