main_menu:
    pattern:    /menu
    defaults:   { _controller: "CoyoteSiteBundle:Main:getMenu"}
    methods:    GET

main_login:
    pattern:    /login
    defaults:   { _controller: "CoyoteSiteBundle:Main:login"}
    methods:    GET

main_language:
    pattern:    /language
    defaults:   { _controller: "CoyoteSiteBundle:Main:postLanguage"}
    methods:    [POST, PUT]

main_index:
    pattern:    /index
    defaults:   { _controller: "CoyoteSiteBundle:Main:index"}
    methods:    GET
