main_login:
    pattern:    /login
    defaults:   { _controller: "CoyoteSiteBundle:Main:login"}

main_menu:
    pattern:    /menu
    defaults:   { _controller: "CoyoteSiteBundle:Menu:menu"}

main_language:
    pattern:    /language
    defaults:   { _controller: "CoyoteSiteBundle:Main:language"}

main_index:
    pattern:    /index
    defaults:   { _controller: "CoyoteSiteBundle:Main:index"}

main_test:
    pattern:    /test
    defaults:   { _controller: "CoyoteSiteBundle:Main:test"}