# index:
#     pattern:    /
#     defaults:   { _controller: "CoyoteSiteBundle:Main:index" }
#
#
# main:
#     pattern:    /
#     defaults:   { _controller: "CoyoteSiteBundle:Main:index" }
#     requirements:
#         _locale: fr|en

main_login:
    pattern:    /login
    defaults:   { _controller: "CoyoteSiteBundle:Main:login", _locale: fr }

main_menu:
    pattern:    /menu
    defaults:   { _controller: "CoyoteSiteBundle:Menu:menu" }

main_language:
    pattern:    /
    defaults:   { _controller: "CoyoteSiteBundle:Main:language"}