profil_changepassword:
    pattern:    /changepassword
    defaults:   { _controller: "CoyoteSiteBundle:ChangePassword:changePassword" }
    methods:    GET

profil_profile:
    pattern:    /
    defaults:   { _controller: "CoyoteSiteBundle:Profile:getprofilUser" }
    methods:    GET

profil_resetting:
    pattern:    /resetting
    defaults:   { _controller: "CoyoteSiteBundle:Profile:resetting"}
    methods:    [POST, PUT]

profil_profile_edit:
    pattern:    /edit
    defaults:   { _controller: "CoyoteSiteBundle:Profile:profiledit"}
    methods:    GET