profil_changepassword:
    pattern:    /changepassword
    defaults:   { _controller: "CoyoteSiteBundle:ChangePassword:changePassword" }

profil_profile:
    pattern:    /
    defaults:   { _controller: "CoyoteSiteBundle:Admin:profil" }

profil_resetting:
    pattern:    /resetting
    defaults:   { _controller: "CoyoteSiteBundle:Admin:resetting"}

profil_profile_edit:
    pattern:    /edit
    defaults:   { _controller: "CoyoteSiteBundle:Admin:profiledit"}

profil_register:
    pattern:    /register
    defaults:   { _controller: "CoyoteSiteBundle:Registration:register"}
