schedule_overtime:
    pattern:    /overtime
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:showovertime"}

schedule_postscheduleuser:
    pattern:    /postscheduleuser
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:postScheduleUser"}

schedule_weekless:
    pattern:    /postscheduleuser/weekless
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:weekless"}
    
schedule_weekmore:
    pattern:    /postscheduleuser/weekmore
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:weekmore"}

schedule_index:
    pattern:    /
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:index"}

schedule_getschedule:
    pattern:    /getSchedule
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:getSchedule"}

schedule_indexshow:
    pattern:    /indexshow
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:indexshow"}

schedule_getscheduleuser:
    pattern:    /getscheduleuser
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:getScheduleUser"}



schedule_print:
    pattern:    /print
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:print"}

schedule_indexprint:
    pattern:    /indexprint
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:indexprint"}

schedule_indexprintyear:
    pattern:    /indexprintyear
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:indexprintyear"}

schedule_printyear:
    pattern:    /scheduleyear
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:printyear"}

schedule_indexexportprintyear:
    pattern:    /indexexportprintyear
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:indexexportprintyear"}

schedule_exportprintyear:
    pattern:    /exportscheduleyear
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:exportprintyear"}

#schedule_absenceday:
#    pattern:    /absenceday
#    defaults:   { _controller: "CoyoteSiteBundle:Schedule:absenceday"}
