schedule_overtime:
    pattern:    /overtime
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:showovertime"}

schedule_savetime:
    pattern:    /scheduleusers/save
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:savetime"}

schedule_savetimefm:
    pattern:    /scheduleframes/save
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:savetimefm"}

schedule_workmore:
    pattern:    /scheduleusers/workmore
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:workmore"}

schedule_workless:
    pattern:    /scheduleusers/workless
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:workless"}

schedule_index:
    pattern:    /
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:index"}

schedule_show:
    pattern:    /show
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:show"}

schedule_indexshow:
    pattern:    /indexshow
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:indexshow"}

schedule_print:
    pattern:    /print
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:print"}

schedule_indexprint:
    pattern:    /indexprint
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:indexprint"}

schedule_post:
    pattern:    /schedule
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:postSchedule"}

schedule_indexprintyear:
    pattern:    /indexprintyear
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:indexprintyear"}

schedule_printyear:
    pattern:    /scheduleyear
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:printyear"}

schedule_indexexportprintyear:
    pattern:    /indexexportprintyear
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:indexexportprintyear"}

schedule_exportprintyear:
    pattern:    /exportscheduleyear
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:exportprintyear"}

#schedule_absenceday:
#    pattern:    /absenceday
#    defaults:   { _controller: "CoyoteSiteBundle:Schedule:absenceday"}
