schedule_overtime:
    pattern:    /overtime
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:showovertime"}
    methods:    GET

schedule_getscheduleuserweek:
    pattern:    /time_attendance
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:getScheduleUserWeek"}
    methods:    GET

schedule_postscheduleuserweek:
    pattern:    /time_attendance_save
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:postScheduleUserWeek"}
    methods:    [POST, PUT]

schedule_postweekless:
    pattern:    /time_attendance/weekless
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:postWeekLess"}
    methods:    GET

schedule_postweekmore:
    pattern:    /time_attendance/weekmore
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:postWeekMore"}
    methods:    GET

schedule_getscheduleusermonth:
    pattern:    /time_attendance_month
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:getScheduleUserMonth"}
    methods:    GET

schedule_getscheduleuserprintmonth:
    pattern:    /time_attendance_print_month
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:getScheduleUserPrintMonth"}
    methods:    GET

schedule_getscheduleuserprintyear:
    pattern:    /time_attendance_print_year
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:getScheduleUserPrintYear"}
    methods:    GET

schedule_postschedules_locked:
    pattern:    /schedules_locked
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:postSchedulesLocked" }
    methods:    GET

schedule_getscheduleuser:
    pattern:    /getscheduleuser
    defaults:   { _controller: "CoyoteSiteBundle:Schedule:getScheduleUser" }
    methods:    GET