servicesfunctions:
    path:     /
    defaults: { _controller: "CoyoteSiteBundle:ServicesFunctions:index" }

servicesfunctions_show:
    path:     /{id}/show
    defaults: { _controller: "CoyoteSiteBundle:ServicesFunctions:show" }

servicesfunctions_new:
    path:     /new
    defaults: { _controller: "CoyoteSiteBundle:ServicesFunctions:new" }

servicesfunctions_create:
    path:     /create
    defaults: { _controller: "CoyoteSiteBundle:ServicesFunctions:create" }
    methods:  POST

servicesfunctions_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoyoteSiteBundle:ServicesFunctions:edit" }

servicesfunctions_update:
    path:     /{id}/update
    defaults: { _controller: "CoyoteSiteBundle:ServicesFunctions:update" }
    methods:  [POST, PUT]

servicesfunctions_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoyoteSiteBundle:ServicesFunctions:delete" }
    methods:  [POST, DELETE]
