coyote_time_savetime:
    pattern:    /timeusers/save
    defaults:   { _controller: "CoyoteSiteBundle:Time:savetime"}

coyote_time_savetimefm:
    pattern:    /timeframes/save
    defaults:   { _controller: "CoyoteSiteBundle:Time:savetimefm"}

coyote_time_workmore:
    pattern:    /timeusers/workmore
    defaults:   { _controller: "CoyoteSiteBundle:Time:workmore"}

coyote_time_workless:
    pattern:    /timeusers/workless
    defaults:   { _controller: "CoyoteSiteBundle:Time:workless"}

coyote_time_index:
    pattern:    /
    defaults:   { _controller: "CoyoteSiteBundle:Time:index"}

coyote_time_show:
    pattern:    /show
    defaults:   { _controller: "CoyoteSiteBundle:Time:show"}

coyote_time_indexshow:
    pattern:    /indexshow
    defaults:   { _controller: "CoyoteSiteBundle:Time:indexshow"}

coyote_time_print:
    pattern:    /print
    defaults:   { _controller: "CoyoteSiteBundle:Time:print"}

coyote_time_indexprint:
    pattern:    /indexprint
    defaults:   { _controller: "CoyoteSiteBundle:Time:indexprint"}

coyote_time_create:
    pattern:    /timecreate
    defaults:   { _controller: "CoyoteSiteBundle:Time:create"}

coyote_time_edit:
    pattern:    /timeedit
    defaults:   { _controller: "CoyoteSiteBundle:Time:edit"}

coyote_time_indexprintyear:
    pattern:    /indexprintyear
    defaults:   { _controller: "CoyoteSiteBundle:Time:indexprintyear"}

coyote_time_printyear:
    pattern:    /timeyear
    defaults:   { _controller: "CoyoteSiteBundle:Time:printyear"}