<?php

/**
 * This file is part of the <name> project.
 *
 * (c) Coyote
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author Coyote
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var integer
     */
    protected $code_car;

    /**
     * @var string
     */
    protected $registration_car;

    /**
     * @var string
     */
    protected $commercial_code;

    /**
     * @var string
     */
    protected $commercial_service;

    /**
     * Set code_car
     *
     * @param integer $codeCar
     *
     * @return User
     */
    public function setCodeCar($codeCar)
    {
        $this->code_car = $codeCar;

        return $this;
    }

    /**
     * Get code_car
     *
     * @return integer
     */
    public function getCodeCar()
    {
        return $this->code_car;
    }

    /**
     * Set registration_car
     *
     * @param string $registrationCar
     *
     * @return User
     */
    public function setRegistrationCar($registrationCar)
    {
        $this->registration_car = $registrationCar;

        return $this;
    }

    /**
     * Get registration_car
     *
     * @return string
     */
    public function getRegistrationCar()
    {
        return $this->registration_car;
    }

    /**
     * Set commercialCode
     *
     * @param boolean $commercialCode
     *
     * @return User
     */
    public function setCommercialCode($commercialCode)
    {
        $this->commercial_code = $commercialCode;

        return $this;
    }

    /**
     * Get commercialCode
     *
     * @return boolean
     */
    public function getCommercialCode()
    {
        return $this->commercial_code;
    }

    /**
     * Set commercialService
     *
     * @param boolean $commercialService
     *
     * @return User
     */
    public function setCommercialService($commercialService)
    {
        $this->commercial_service = $commercialService;

        return $this;
    }

    /**
     * Get commercialService
     *
     * @return boolean
     */
    public function getCommercialService()
    {
        return $this->commercial_service;
    }

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

}
