services:
    coyote_attendance.admin.schedule:
        class: Coyote\Bundle\AttendanceBundle\Admin\ScheduleAdmin
        arguments: [~, Coyote\Bundle\AttendanceBundle\Entity\Schedule, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Schedule, label: Schedule }
