services:
    coyote_directory.admin.directory:
        class: Coyote\Bundle\DirectoryBundle\Admin\DirectoryAdmin
        arguments: [~, Coyote\Bundle\DirectoryBundle\Entity\Directory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Directory, label: Directory }
